# Generated by Django 4.1 on 2022-08-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='posts',
            new_name='post',
        ),
    ]
